name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        uses: azure/setup-azure-cli@v1

      - name: Log in to Azure
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CREDENTIALS.clientId }} -p ${{ secrets.AZURE_CREDENTIALS.clientSecret }} --tenant ${{ secrets.AZURE_CREDENTIALS.tenantId }}
        # You can also set the default subscription using:
        # az account set --subscription ${{ secrets.AZURE_CREDENTIALS.subscriptionId }}

      # Add your deployment steps here
      - name: Deploy to Azure Web App
        run: |
          # Your deployment commands here
