name: Deploy .NET App to Azure Web App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'
env:
  WEBAPP_NAME: sample-net-app-kasun    # Azure Web App Name
  WEBAPP_PACKAGE_PATH: '.'      # Project Path Location default to root(.)
  NUGET_VERSION: '5.3.1'           # dot net version to use

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:

    # checkout the repo
    - uses: actions/checkout@master  
    
    - name: Install Nuget
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: ${{ env.NUGET_VERSION}}
    - name: NuGet to restore dependencies 
      run: nuget restore
  
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.0

    - name: Run MSBuild
      run: msbuild .\SampleWebApplication.sln
       
    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.WEBAPP_NAME }} 
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }} 
        package: '${{ env.WEBAPP_PACKAGE_PATH }}/SampleWebApplication/'
